param([string]$buildPath)
Import-Module "$PSScriptRoot\templates\ReadmeGenerationUtilities.psm1"

Write-Host "===================== Generating Readme Markdown ====================="
$markdown = "<!-- Do not edit this file directly. The README.md file is auto-generated during the build process, and any changes you make will be overwritten. If you need to make changes to this file, update the /build-scripts/templates/ReadmeTemplate.md file.  -->`r`n"
$markdown += Get-Content "$($buildPath)build-scripts\templates\ReadmeTemplate.md" -Raw

Set-Content -Path "$($buildPath)README.md" -Value $ExecutionContext.InvokeCommand.ExpandString($markdown)
