name: Build Test and Deploy Template

on:
  workflow_call:
    inputs:
        buildConfig:
            description: 'Build Configuration'
            required: true
            default: 'Debug'
            type: string
        versionPrefix:
            description: 'Version Number'
            required: false
            default: ''
            type: string
        versionSuffix:
            description: 'Version Suffix'
            required: false
            default: '-alpha'
            type: string
    secrets:
        NUGET_KEY: 
            required: true


jobs:
  build-test-deploy:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]
    env:
      BUILD_WORKSPACE_PATH: ${{ github.workspace }}
      INPUT_BUILD_CONFIG: ${{ inputs.buildConfig }}
      INPUT_VERSION_PREFIX: ${{ inputs.versionPrefix }}
      INPUT_VERSION_SUFFIX: ${{ inputs.versionSuffix }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Set version number
        run: |
          ${{ env.BUILD_WORKSPACE_PATH }}/build-scripts/set-version-property.ps1 '${{ env.INPUT_BUILD_CONFIG }}' '${{ env.INPUT_VERSION_SUFFIX }}' '${{ env.INPUT_VERSION_PREFIX }}'
          ${{ env.BUILD_WORKSPACE_PATH }}/build-scripts/setenv.ps1
        shell: pwsh
      - name: Build / Pack
        shell: pwsh
        run: ${{ env.BUILD_WORKSPACE_PATH }}/build-scripts/build.ps1 -buildType '${{ env.INPUT_BUILD_CONFIG }}' -versionSuffix '${{ env.BUILD_VERSION_SUFFIX }}' -versionPrefix '${{ env.BUILD_VERSION_PREFIX }}'
      - name: Test
        shell: pwsh
        run: dotnet test --no-build --no-restore --configuration '${{ env.INPUT_BUILD_CONFIG }}' --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

      - name: Create Deployment Packages
        shell: pwsh
        run: |
          Compress-Archive -Path "${{ env.BUILD_WORKSPACE_PATH }}/${{ env.REPO_PKGNAME }}/bin/${{ env.INPUT_BUILD_CONFIG }}/*", README.md, LICENSE -DestinationPath "${{ env.BUILD_WORKSPACE_PATH }}/${{ env.REPO_PKGNAME }}.${{ env.PKGVERSION }}.zip"

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: REPO-${{ env.PKGVERSION }} 
          release_name: Release ${{ env.REPO_PKGNAME }}
          draft: true
          prerelease: true
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: "${{ env.BUILD_WORKSPACE_PATH }}/${{ env.REPO_PKGNAME }}.${{ env.PKGVERSION }}.zip"
          asset_name: "${{ env.REPO_PKGNAME }}.${{ env.PKGVERSION }}.zip"
          asset_content_type: application/zip
      - name: Publish the packages to GPR
        run: dotnet nuget push ${{ env.BUILD_WORKSPACE_PATH }}/**/*.nupkg  -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -k ${{secrets.GITHUB_TOKEN }} --skip-duplicate
      - name: Publish the source packages to GPR
        run: dotnet nuget push ${{ env.BUILD_WORKSPACE_PATH }}/**/*.snupkg -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -k ${{secrets.GITHUB_TOKEN }} --skip-duplicate

      - name: Publish the packages to NuGet
        run: dotnet nuget push ${{ env.BUILD_WORKSPACE_PATH }}/**/*.nupkg  -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_KEY }} --skip-duplicate
      - name: Publish the source packages to NuGet
        run: dotnet nuget push ${{ env.BUILD_WORKSPACE_PATH }}/**/*.snupkg  -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_KEY }} --skip-duplicate
      #- name: Generate README.md
      #  shell: pwsh
      #  run: |
      #    cd ${{ github.workspace }}
      #    git checkout ${{ env.GITHUB_REF_NAME }}
      #    git config --global user.name "${{ env.GITHUB_REPOSITORY }} Continuous Integration"
      #    git config --global user.email "${{ env.GITHUB_ACTOR }}@users.noreply.github.com"
      #    git config pull.rebase false
      #    git pull origin staging
      #    git pull origin main
      #    ${{ github.workspace }}/build-scripts/generate-readme.ps1 -buildPath "${{ github.workspace }}\"
      #    git add README.md
      #    git commit -m "${{ env.GITHUB_RUN_ID }} - Generated README.md from template"
      #    git push origin ${{ env.GITHUB_REF_NAME }}

